// GENERATED by tools/gen_kotlin.py from the pydantic models in
// packages/rover_contracts -- do not edit by hand.
//
// Regenerate, from the repository root:
//   PYTHONPATH=packages .venv/bin/python tools/gen_kotlin.py
// Check for drift (exit 1 when this file is stale):
//   PYTHONPATH=packages .venv/bin/python tools/gen_kotlin.py --check
//
// Every bound the Pi enforces at parse time is an `init { require(...) }`
// here: numeric ranges, string lengths and patterns, list sizes, literal
// constants and closed string sets.  Cross-field rules written as pydantic
// model validators (power != 0, args matching skill, ordered limits) are not
// in the JSON schema and are NOT generated; a host built on these classes
// must add them in its own validator.
//
// Mapping: an integer with a closed range that fits Int -> Int, any other
// integer -> Long; number -> Double; a closed string enum -> enum class with
// @SerialName; X | null -> X?; an untagged union -> JsonObject.  Every property
// with a default carries @EncodeDefault, so an encoded object has every key
// pydantic's model_dump() emits, in the same order.  Decode with the default
// Json(): unknown keys, lenient literals and NaN/Infinity are then refused, as
// extra="forbid" and allow_inf_nan=False refuse them on the Pi.
//
// Order: enums first, then classes, each sorted by name; properties in the
// pydantic declaration order.

@file:OptIn(ExperimentalSerializationApi::class)

package dev.rover.contracts

import kotlinx.serialization.EncodeDefault
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

/** What a client declares it will do, in ``hello.caps``. */
@Serializable
enum class BusCap {
    @SerialName("skill") SKILL,
    @SerialName("twist") TWIST,
    @SerialName("subscribe") SUBSCRIBE,
}

/** How sure the model is that it found the object. */
@Serializable
enum class Confidence {
    @SerialName("low") LOW,
    @SerialName("medium") MEDIUM,
    @SerialName("high") HIGH,
}

/** ``set_face`` expressions, rendered by rover-web's face page. */
@Serializable
enum class Face {
    @SerialName("neutral") NEUTRAL,
    @SerialName("happy") HAPPY,
    @SerialName("thinking") THINKING,
    @SerialName("confused") CONFUSED,
    @SerialName("alert") ALERT,
    @SerialName("sleepy") SLEEPY,
}

/**
 * Model-reported hazards.
 *
 * ``text_in_frame`` drives ARCHITECTURE 6's speed cap, which is a
 * **model-reported mitigation, not a deterministic control**: its only input
 * is a field the model itself writes, and an attacker who put text in the
 * frame is the same party writing it (A12).  It is reported at G1 beside the
 * attack-success rate, never counted among the Pi-side controls.
 */
@Serializable
enum class Hazard {
    @SerialName("clutter") CLUTTER,
    @SerialName("text_in_frame") TEXT_IN_FRAME,
    @SerialName("stairs") STAIRS,
    @SerialName("drop_off") DROP_OFF,
    @SerialName("people") PEOPLE,
    @SerialName("low_light") LOW_LIGHT,
}

/** Scene illumination, which bounds how far the vision answer is worth. */
@Serializable
enum class Lighting {
    @SerialName("dark") DARK,
    @SerialName("dim") DIM,
    @SerialName("normal") NORMAL,
    @SerialName("bright") BRIGHT,
}

/** ``result.reason``, a speakable enum.  ``NONE`` is the empty string. */
@Serializable
enum class ResultReason {
    @SerialName("") NONE,
    @SerialName("unknown_skill") UNKNOWN_SKILL,
    @SerialName("bad_args") BAD_ARGS,
    @SerialName("out_of_bounds") OUT_OF_BOUNDS,
    @SerialName("power_clamped") POWER_CLAMPED,
    @SerialName("stale_seq") STALE_SEQ,
    @SerialName("duplicate_cmd") DUPLICATE_CMD,
    @SerialName("stale_turn") STALE_TURN,
    @SerialName("goal_ttl_too_long") GOAL_TTL_TOO_LONG,
    @SerialName("goal_ttl_too_short") GOAL_TTL_TOO_SHORT,
    @SerialName("ttl_expired") TTL_EXPIRED,
    @SerialName("not_ready") NOT_READY,
    @SerialName("faulted") FAULTED,
    @SerialName("obstacle") OBSTACLE,
    @SerialName("budget_exceeded") BUDGET_EXCEEDED,
    @SerialName("rate_limited") RATE_LIMITED,
    @SerialName("obs_stale") OBS_STALE,
    @SerialName("source_not_allowed") SOURCE_NOT_ALLOWED,
    @SerialName("unauthorized_utterance") UNAUTHORIZED_UTTERANCE,
    @SerialName("unpatched_firmware") UNPATCHED_FIRMWARE,
    @SerialName("heading_unavailable") HEADING_UNAVAILABLE,
    @SerialName("feedback_stale") FEEDBACK_STALE,
    @SerialName("estop_active") ESTOP_ACTIVE,
    @SerialName("box_lost") BOX_LOST,
}

/** ``result.status``.  There is no ``fault``: a fault is ``aborted``. */
@Serializable
enum class ResultStatus {
    @SerialName("accepted") ACCEPTED,
    @SerialName("done") DONE,
    @SerialName("rejected") REJECTED,
    @SerialName("preempted") PREEMPTED,
    @SerialName("aborted") ABORTED,
    @SerialName("timeout") TIMEOUT,
}

/** The seven skills the model may emit (ARCHITECTURE 6, ADR-0013). */
@Serializable
enum class SkillName {
    @SerialName("drive_for") DRIVE_FOR,
    @SerialName("turn_to") TURN_TO,
    @SerialName("stop") STOP,
    @SerialName("say") SAY,
    @SerialName("describe_scene") DESCRIBE_SCENE,
    @SerialName("find") FIND,
    @SerialName("set_face") SET_FACE,
}

/** ``source`` on the robotd bus, bound to the connection at ``hello``. */
@Serializable
enum class Source {
    @SerialName("brain") BRAIN,
    @SerialName("web") WEB,
    @SerialName("teleop") TELEOP,
    @SerialName("phone") PHONE,
}

@Serializable
data class DescribeSceneCall(
    val speech: String,
    val skill: String,
    val args: NoArgs,
) {
    init {
        require(speech.length <= 160) { "invalid speech: $speech" }
        require(skill == "describe_scene") { "invalid skill: $skill" }
    }
}

/**
 * ``drive_for`` as the model writes it.  Open loop: a power for a time.
 *
 * ``power_pct`` is a legacy name for hundredths of a Waveshare power unit:
 * 30 means 0.30, or 60% duty at full scale 0.5. The sign is the direction.
 * Zero is not a drive.
 */
@Serializable
data class DriveForArgs(
    @SerialName("duration_ms") val durationMs: Int,
    @SerialName("power_pct") val powerPct: Int,
) {
    init {
        require(durationMs >= 100 && durationMs <= 2000) { "invalid duration_ms: $durationMs" }
        require(powerPct >= -30 && powerPct <= 30) { "invalid power_pct: $powerPct" }
    }
}

/**
 * ``drive_for`` on the bus.  ``power`` is in Waveshare units (full scale
 * 0.5); above ``[limits] power_max`` it is clamped, not rejected.  0.30 is the
 * absolute bound: the firmware fork clamps there too, so robotd can never
 * send more than the controller would apply.
 */
@Serializable
data class DriveForBusArgs(
    @SerialName("duration_s") val durationS: Double,
    val power: Double,
) {
    init {
        require(durationS > 0.0 && durationS <= 2.0) { "invalid duration_s: $durationS" }
        require(power >= -0.3 && power <= 0.3) { "invalid power: $power" }
    }
}

@Serializable
data class DriveForCall(
    val speech: String,
    val skill: String,
    val args: DriveForArgs,
) {
    init {
        require(speech.length <= 160) { "invalid speech: $speech" }
        require(skill == "drive_for") { "invalid skill: $skill" }
    }
}

/**
 * Stop-class.  The web STOP button is never behind the model or the
 * validator, and is one of the three counted stop authorities (A29).
 */
@Serializable
data class EstopMessage(
    @EncodeDefault val v: Int = 1,
    @EncodeDefault val type: String = "estop",
    val source: Source,
    @EncodeDefault val reason: String? = null,
) {
    init {
        require(v == 1) { "invalid v: $v" }
        require(type == "estop") { "invalid type: $type" }
        require(reason == null || reason.length <= 64) { "invalid reason: $reason" }
    }
}

/** ``find``: a stationary scan of at most eight 45 degree sweeps (A14). */
@Serializable
data class FindArgs(
    @SerialName("object") val object_: String,
    @SerialName("max_sweeps") val maxSweeps: Int,
) {
    init {
        require(object_.length >= 1 && object_.length <= 48) { "invalid object: $object_" }
        require(maxSweeps >= 1 && maxSweeps <= 8) { "invalid max_sweeps: $maxSweeps" }
    }
}

@Serializable
data class FindCall(
    val speech: String,
    val skill: String,
    val args: FindArgs,
) {
    init {
        require(speech.length <= 160) { "invalid speech: $speech" }
        require(skill == "find") { "invalid skill: $skill" }
    }
}

/**
 * The answer to one ``find`` sweep.
 *
 * ``center_x_permille`` is 0..1000 across the frame; it is meaningless when
 * ``present`` is false and the executor ignores it then.
 */
@Serializable
data class FindObservation(
    val kind: String,
    val present: Boolean,
    @SerialName("center_x_permille") val centerXPermille: Int,
    val confidence: Confidence,
    val description: String,
) {
    init {
        require(kind == "find") { "invalid kind: $kind" }
        require(centerXPermille >= 0 && centerXPermille <= 1000) {
            "invalid center_x_permille: $centerXPermille"
        }
        require(description.length <= 240) { "invalid description: $description" }
    }
}

/** Binds ``source`` to the connection; a second ``hello`` is refused. */
@Serializable
data class HelloMessage(
    @EncodeDefault val v: Int = 1,
    @EncodeDefault val type: String = "hello",
    val source: Source,
    val pid: Long,
    val caps: List<BusCap>,
) {
    init {
        require(v == 1) { "invalid v: $v" }
        require(type == "hello") { "invalid type: $type" }
        require(pid > 0L) { "invalid pid: $pid" }
        require(caps.size >= 1) { "invalid caps: $caps" }
    }
}

/** ``[limits]``, republished verbatim as ``welcome.limits``. */
@Serializable
data class LimitsConfig(
    @SerialName("power_max") @EncodeDefault val powerMax: Double = 0.3,
    @SerialName("power_default") @EncodeDefault val powerDefault: Double = 0.2,
    @SerialName("power_min") @EncodeDefault val powerMin: Double = 0.08,
    @SerialName("drive_for_max_s") @EncodeDefault val driveForMaxS: Double = 2.0,
    @SerialName("turn_timeout_max_s") @EncodeDefault val turnTimeoutMaxS: Double = 4.0,
    @SerialName("turn_tolerance_deg") @EncodeDefault val turnToleranceDeg: Double = 5.0,
    @SerialName("turn_kp") @EncodeDefault val turnKp: Double = 0.004,
    @SerialName("goal_ttl_ms_max") @EncodeDefault val goalTtlMsMax: Long = 5000L,
    @SerialName("budget_motion_s") @EncodeDefault val budgetMotionS: Double = 12.0,
    @SerialName("motion_cooldown_ms") @EncodeDefault val motionCooldownMs: Long = 3000L,
    @SerialName("twist_power") @EncodeDefault val twistPower: Double = 0.3,
    @SerialName("twist_renew_ms") @EncodeDefault val twistRenewMs: Long = 200L,
) {
    init {
        require(powerMax > 0.0) { "invalid power_max: $powerMax" }
        require(powerDefault > 0.0) { "invalid power_default: $powerDefault" }
        require(powerMin >= 0.0) { "invalid power_min: $powerMin" }
        require(driveForMaxS > 0.0) { "invalid drive_for_max_s: $driveForMaxS" }
        require(turnTimeoutMaxS > 0.0) { "invalid turn_timeout_max_s: $turnTimeoutMaxS" }
        require(turnToleranceDeg >= 2.0) { "invalid turn_tolerance_deg: $turnToleranceDeg" }
        require(turnKp > 0.0) { "invalid turn_kp: $turnKp" }
        require(goalTtlMsMax >= 100L) { "invalid goal_ttl_ms_max: $goalTtlMsMax" }
        require(budgetMotionS > 0.0) { "invalid budget_motion_s: $budgetMotionS" }
        require(motionCooldownMs >= 0L) { "invalid motion_cooldown_ms: $motionCooldownMs" }
        require(twistPower > 0.0) { "invalid twist_power: $twistPower" }
        require(twistRenewMs > 0L) { "invalid twist_renew_ms: $twistRenewMs" }
    }
}

/** What is left of the per-instruction budget of I-15: motion seconds. */
@Serializable
data class MotionBudget(
    val seconds: Long,
) {
    init {
        require(seconds >= 0L) { "invalid seconds: $seconds" }
    }
}

/** ``{}`` -- ``stop`` and ``describe_scene`` take no arguments. */
@Serializable
object NoArgs

/** One entry of the scene ring: what, which heading, how long ago. */
@Serializable
data class RecentlySeen(
    val label: String,
    @SerialName("heading_deg") val headingDeg: Int,
    @SerialName("age_s") val ageS: Long,
) {
    init {
        require(label.length >= 1 && label.length <= 48) { "invalid label: $label" }
        require(headingDeg >= 0 && headingDeg <= 359) { "invalid heading_deg: $headingDeg" }
        require(ageS >= 0L) { "invalid age_s: $ageS" }
    }
}

/** What a completed or clamped command reports back. */
@Serializable
data class ResultDetail(
    @SerialName("duration_ms") @EncodeDefault val durationMs: Long? = null,
    @SerialName("turned_deg") @EncodeDefault val turnedDeg: Double? = null,
    @SerialName("heading_error_deg") @EncodeDefault val headingErrorDeg: Double? = null,
    @SerialName("power_clamped_to") @EncodeDefault val powerClampedTo: Double? = null,
) {
    init {
        require(durationMs == null || durationMs >= 0L) { "invalid duration_ms: $durationMs" }
        require(powerClampedTo == null || (powerClampedTo >= 0.0 && powerClampedTo <= 0.3)) {
            "invalid power_clamped_to: $powerClampedTo"
        }
    }
}

/** The outcome of one ``cmd_id``. */
@Serializable
data class ResultMessage(
    @EncodeDefault val v: Int = 1,
    @EncodeDefault val type: String = "result",
    @SerialName("cmd_id") val cmdId: String,
    @EncodeDefault val seq: Long? = null,
    val status: ResultStatus,
    @EncodeDefault val reason: ResultReason = ResultReason.NONE,
    @EncodeDefault val detail: ResultDetail? = null,
    @SerialName("t_utc_ns") val tUtcNs: Long,
) {
    init {
        require(v == 1) { "invalid v: $v" }
        require(type == "result") { "invalid type: $type" }
        require(Regex("^[0-7][0-9A-HJKMNP-TV-Z]{25}\$").matches(cmdId)) { "invalid cmd_id: $cmdId" }
        require(seq == null || seq >= 0L) { "invalid seq: $seq" }
        require(tUtcNs >= 0L) { "invalid t_utc_ns: $tUtcNs" }
    }
}

/**
 * ``[safety]``, republished verbatim as ``welcome.safety``.
 *
 * ``heartbeat_ms``, ``tof_stop_mm`` and ``low_battery_v`` are mirrors of
 * constants the firmware fork compiles in.  Editing them here changes nothing
 * on the controller: robotd compares ``heartbeat_ms`` with the value in the
 * boot banner and refuses to move when they disagree.
 */
@Serializable
data class SafetyConfig(
    @SerialName("obs_max_age_ms") @EncodeDefault val obsMaxAgeMs: Long = 5000L,
    @SerialName("heartbeat_ms") @EncodeDefault val heartbeatMs: Long = 300L,
    @SerialName("feedback_max_age_ms") @EncodeDefault val feedbackMaxAgeMs: Long = 150L,
    @SerialName("tof_stop_mm") @EncodeDefault val tofStopMm: Long = 250L,
    @SerialName("low_battery_v") @EncodeDefault val lowBatteryV: Double = 9.9,
    @SerialName("require_patched_firmware") @EncodeDefault val requirePatchedFirmware: Boolean = true,
) {
    init {
        require(obsMaxAgeMs > 0L) { "invalid obs_max_age_ms: $obsMaxAgeMs" }
        require(heartbeatMs >= 50L) { "invalid heartbeat_ms: $heartbeatMs" }
        require(feedbackMaxAgeMs > 0L) { "invalid feedback_max_age_ms: $feedbackMaxAgeMs" }
        require(tofStopMm > 0L) { "invalid tof_stop_mm: $tofStopMm" }
        require(lowBatteryV > 0.0) { "invalid low_battery_v: $lowBatteryV" }
    }
}

/** ``say`` as the model writes it. */
@Serializable
data class SayArgs(
    val text: String,
) {
    init {
        require(text.length >= 1 && text.length <= 240) { "invalid text: $text" }
    }
}

/** ``say`` on the bus: this is where the 300-character bound lives. */
@Serializable
data class SayBusArgs(
    val text: String,
) {
    init {
        require(text.length >= 1 && text.length <= 300) { "invalid text: $text" }
    }
}

@Serializable
data class SayCall(
    val speech: String,
    val skill: String,
    val args: SayArgs,
) {
    init {
        require(speech.length <= 160) { "invalid speech: $speech" }
        require(skill == "say") { "invalid skill: $skill" }
    }
}

/** The answer to ``describe_scene``, spoken back through ``say``. */
@Serializable
data class SceneObservation(
    val kind: String,
    val description: String,
    val labels: List<String>,
    val lighting: Lighting,
    val hazards: List<Hazard>,
) {
    init {
        require(kind == "scene") { "invalid kind: $kind" }
        require(description.length <= 240) { "invalid description: $description" }
        require(labels.size <= 12 && labels.all { it.length >= 1 && it.length <= 32 }) {
            "invalid labels: $labels"
        }
        require(hazards.size <= 6) { "invalid hazards: $hazards" }
    }
}

/** ``set_face``. */
@Serializable
data class SetFaceArgs(
    val expr: Face,
)

@Serializable
data class SetFaceCall(
    val speech: String,
    val skill: String,
    val args: SetFaceArgs,
) {
    init {
        require(speech.length <= 160) { "invalid speech: $speech" }
        require(skill == "set_face") { "invalid skill: $skill" }
    }
}

/**
 * A dispatched skill.  ``issued_mono_ns`` is the sender's clock and is
 * never compared against robotd's, which stamps its own ``recv_mono_ns``.
 */
@Serializable
data class SkillMessage(
    @EncodeDefault val v: Int = 1,
    @EncodeDefault val type: String = "skill",
    val source: Source,
    @SerialName("cmd_id") val cmdId: String,
    val seq: Long,
    @SerialName("turn_id") val turnId: String,
    @SerialName("issued_mono_ns") val issuedMonoNs: Long,
    @SerialName("goal_ttl_ms") val goalTtlMs: Int,
    val skill: String,
    /** One of DriveForBusArgs, TurnToBusArgs, SayBusArgs, FindArgs, SetFaceArgs, NoArgs, untagged: decode with the class the sibling discriminator selects. */
    val args: JsonObject,
    @EncodeDefault val obs: SkillObs? = null,
    @EncodeDefault val trace: SkillTrace? = null,
) {
    init {
        require(v == 1) { "invalid v: $v" }
        require(type == "skill") { "invalid type: $type" }
        require(Regex("^[0-7][0-9A-HJKMNP-TV-Z]{25}\$").matches(cmdId)) { "invalid cmd_id: $cmdId" }
        require(seq >= 0L) { "invalid seq: $seq" }
        require(Regex("^[0-7][0-9A-HJKMNP-TV-Z]{25}\$").matches(turnId)) {
            "invalid turn_id: $turnId"
        }
        require(issuedMonoNs >= 0L) { "invalid issued_mono_ns: $issuedMonoNs" }
        require(goalTtlMs >= 100 && goalTtlMs <= 5000) { "invalid goal_ttl_ms: $goalTtlMs" }
        require(skill in setOf("drive_for", "turn_to", "say", "describe_scene", "find", "set_face")) {
            "invalid skill: $skill"
        }
    }
}

/** The frame that justifies a motion skill; robotd gates on its age (I-23). */
@Serializable
data class SkillObs(
    @SerialName("frame_id") val frameId: String,
    @SerialName("frame_mono_ns") val frameMonoNs: Long,
) {
    init {
        require(Regex("^cam-\\d{6}\$").matches(frameId)) { "invalid frame_id: $frameId" }
        require(frameMonoNs >= 0L) { "invalid frame_mono_ns: $frameMonoNs" }
    }
}

/** Provenance, asserted per trial at G1.  ``authorized_motion`` rides here. */
@Serializable
data class SkillTrace(
    @EncodeDefault val model: String? = null,
    @SerialName("prompt_sha256") @EncodeDefault val promptSha256: String? = null,
    @SerialName("authorized_motion") @EncodeDefault val authorizedMotion: Boolean? = null,
) {
    init {
        require(model == null || model.length <= 128) { "invalid model: $model" }
        require(promptSha256 == null || promptSha256.length <= 64) {
            "invalid prompt_sha256: $promptSha256"
        }
    }
}

@Serializable
data class StateActive(
    @SerialName("cmd_id") val cmdId: String,
    val skill: String,
    val source: Source,
    val progress: Double,
    @SerialName("deadline_in_ms") val deadlineInMs: Long,
) {
    init {
        require(Regex("^[0-7][0-9A-HJKMNP-TV-Z]{25}\$").matches(cmdId)) { "invalid cmd_id: $cmdId" }
        require(skill in setOf("drive_for", "turn_to", "say", "describe_scene", "find", "set_face")) {
            "invalid skill: $skill"
        }
        require(progress >= 0.0 && progress <= 1.0) { "invalid progress: $progress" }
        require(deadlineInMs >= 0L) { "invalid deadline_in_ms: $deadlineInMs" }
    }
}

/**
 * From the board's INA219 bus voltage.  No current or open-circuit
 * estimate: the board does not report them.
 */
@Serializable
data class StateBattery(
    @SerialName("pack_v") val packV: Double,
    val pct: Int,
) {
    init {
        require(packV >= 0.0) { "invalid pack_v: $packV" }
        require(pct >= 0 && pct <= 100) { "invalid pct: $pct" }
    }
}

/**
 * What I-15's per-instruction budget has left on the current instruction,
 * from the one ledger that enforces it.  Open loop, so the budget is motion
 * time: robotd charges every 20 ms slot in which it streamed a non-zero
 * command, and a dispatch-time estimate booked elsewhere is not the budget
 * robotd applies.
 */
@Serializable
data class StateBudget(
    @SerialName("motion_s") val motionS: Double,
) {
    init {
        require(motionS >= 0.0) { "invalid motion_s: $motionS" }
    }
}

/**
 * Published at ``[bus] state_hz`` and on any change of ``rover.hb_ok``,
 * ``rover.stop_flags``, ``rover.fw``, ``active.cmd_id`` or ``ready``.
 */
@Serializable
data class StateMessage(
    @EncodeDefault val v: Int = 1,
    @EncodeDefault val type: String = "state",
    @SerialName("t_utc_ns") val tUtcNs: Long,
    @SerialName("t_mono_ns") val tMonoNs: Long,
    val rover: StateRover,
    val twist: StateTwist,
    @SerialName("front_m") @EncodeDefault val frontM: Double? = null,
    val bumper: Boolean,
    @SerialName("estop_sw") val estopSw: Boolean,
    val battery: StateBattery,
    @EncodeDefault val active: StateActive? = null,
    val budget: StateBudget,
    val ready: Boolean,
    @EncodeDefault val reason: String = "",
) {
    init {
        require(v == 1) { "invalid v: $v" }
        require(type == "state") { "invalid type: $type" }
        require(tUtcNs >= 0L) { "invalid t_utc_ns: $tUtcNs" }
        require(tMonoNs >= 0L) { "invalid t_mono_ns: $tMonoNs" }
        require(frontM == null || frontM >= 0.0) { "invalid front_m: $frontM" }
        require(reason.length <= 64) { "invalid reason: $reason" }
    }
}

/**
 * What the controller last reported, with robotd's arrival stamp.
 *
 * ``fw`` is ``null`` for stock firmware, and that alone makes ``ready``
 * false: a controller without the fork's heartbeat and cap is not one robotd
 * will drive.  ``heading_deg`` is the fused yaw in (-180, 180], sign already
 * corrected by ``[link] yaw_sign``.
 */
@Serializable
data class StateRover(
    @EncodeDefault val fw: String? = null,
    @SerialName("hb_ok") val hbOk: Boolean,
    @SerialName("stop_flags") val stopFlags: Int,
    @SerialName("feedback_age_ms") val feedbackAgeMs: Long,
    @SerialName("cmd_left") val cmdLeft: Double,
    @SerialName("cmd_right") val cmdRight: Double,
    @SerialName("heading_deg") val headingDeg: Double,
    @SerialName("yaw_rate_dps") @EncodeDefault val yawRateDps: Double? = null,
    @SerialName("roll_deg") val rollDeg: Double,
    @SerialName("pitch_deg") val pitchDeg: Double,
    @SerialName("temp_c") val tempC: Double,
    @SerialName("clamp_count") val clampCount: Int,
    val motion: Boolean,
) {
    init {
        require(fw == null || fw.length <= 32) { "invalid fw: $fw" }
        require(stopFlags >= 0 && stopFlags <= 31) { "invalid stop_flags: $stopFlags" }
        require(feedbackAgeMs >= 0L) { "invalid feedback_age_ms: $feedbackAgeMs" }
        require(cmdLeft >= -0.5 && cmdLeft <= 0.5) { "invalid cmd_left: $cmdLeft" }
        require(cmdRight >= -0.5 && cmdRight <= 0.5) { "invalid cmd_right: $cmdRight" }
        require(headingDeg > -180.0 && headingDeg <= 180.0) { "invalid heading_deg: $headingDeg" }
        require(clampCount >= 0 && clampCount <= 65535) { "invalid clamp_count: $clampCount" }
    }
}

/** The command robotd is currently streaming, in power units. */
@Serializable
data class StateTwist(
    val lin: Double,
    val ang: Double,
) {
    init {
        require(lin >= -0.3 && lin <= 0.3) { "invalid lin: $lin" }
        require(ang >= -0.3 && ang <= 0.3) { "invalid ang: $ang" }
    }
}

@Serializable
data class StopCall(
    val speech: String,
    val skill: String,
    val args: NoArgs,
) {
    init {
        require(speech.length <= 160) { "invalid speech: $speech" }
        require(skill == "stop") { "invalid skill: $skill" }
    }
}

/**
 * Stop-class, and deliberately the loosest message on the bus: no required
 * ``seq``, ``cmd_id`` or ``turn_id``, because brain's restart path sends one
 * before any turn exists and because I-22 forbids ever answering it
 * ``rejected``.  A parse failure here must never become a rejection.
 */
@Serializable
data class StopMessage(
    @EncodeDefault val v: Int = 1,
    @EncodeDefault val type: String = "stop",
    val source: Source,
    @EncodeDefault val reason: String? = null,
    @SerialName("cmd_id") @EncodeDefault val cmdId: String? = null,
    @SerialName("turn_id") @EncodeDefault val turnId: String? = null,
    @EncodeDefault val seq: Long? = null,
) {
    init {
        require(v == 1) { "invalid v: $v" }
        require(type == "stop") { "invalid type: $type" }
        require(reason == null || reason.length <= 64) { "invalid reason: $reason" }
        require(cmdId == null || Regex("^[0-7][0-9A-HJKMNP-TV-Z]{25}\$").matches(cmdId)) {
            "invalid cmd_id: $cmdId"
        }
        require(turnId == null || Regex("^[0-7][0-9A-HJKMNP-TV-Z]{25}\$").matches(turnId)) {
            "invalid turn_id: $turnId"
        }
        require(seq == null || seq >= 0L) { "invalid seq: $seq" }
    }
}

/**
 * ``turn_to`` as the model writes it: an absolute compass-style heading in
 * whole degrees, 0..359, in the frame the WorldState's ``heading_deg`` uses.
 * Host headings increase leftward. Turn left 90 with
 * ``(heading + 90) mod 360``.
 */
@Serializable
data class TurnToArgs(
    @SerialName("heading_deg") val headingDeg: Int,
) {
    init {
        require(headingDeg >= 0 && headingDeg <= 359) { "invalid heading_deg: $headingDeg" }
    }
}

/**
 * ``turn_to`` on the bus: an absolute heading, a deadline, a tolerance.
 * robotd closes the loop on the rover's fused yaw; there is no encoder.
 */
@Serializable
data class TurnToBusArgs(
    @SerialName("heading_deg") val headingDeg: Double,
    @SerialName("timeout_s") @EncodeDefault val timeoutS: Double = 4.0,
    @SerialName("tolerance_deg") @EncodeDefault val toleranceDeg: Double = 5.0,
) {
    init {
        require(headingDeg >= 0.0 && headingDeg < 360.0) { "invalid heading_deg: $headingDeg" }
        require(timeoutS > 0.0 && timeoutS <= 4.0) { "invalid timeout_s: $timeoutS" }
        require(toleranceDeg >= 2.0 && toleranceDeg <= 20.0) {
            "invalid tolerance_deg: $toleranceDeg"
        }
    }
}

@Serializable
data class TurnToCall(
    val speech: String,
    val skill: String,
    val args: TurnToArgs,
) {
    init {
        require(speech.length <= 160) { "invalid speech: $speech" }
        require(skill == "turn_to") { "invalid skill: $skill" }
    }
}

/** A stream is one arbitration unit; it has no goal TTL and no ``turn_id``. */
@Serializable
data class TwistMessage(
    @EncodeDefault val v: Int = 1,
    @EncodeDefault val type: String = "twist",
    val source: Source,
    @SerialName("cmd_id") val cmdId: String,
    val seq: Long,
    val twist: TwistPayload,
) {
    init {
        require(v == 1) { "invalid v: $v" }
        require(type == "twist") { "invalid type: $type" }
        require(Regex("^[0-7][0-9A-HJKMNP-TV-Z]{25}\$").matches(cmdId)) { "invalid cmd_id: $cmdId" }
        require(seq >= 0L) { "invalid seq: $seq" }
    }
}

/**
 * A35's streamed command, renewed every 200 ms or it lapses.  Open loop, so
 * both axes are in power units: ``lin`` drives both sides, ``ang`` is added to
 * the right and subtracted from the left, and each side is then clamped.
 */
@Serializable
data class TwistPayload(
    val lin: Double,
    val ang: Double,
) {
    init {
        require(lin >= -0.3 && lin <= 0.3) { "invalid lin: $lin" }
        require(ang >= -0.3 && ang <= 0.3) { "invalid ang: $ang" }
    }
}

/**
 * Republishes every ``[limits]`` and ``[safety]`` key, so a gate asserts
 * against what is running rather than against the file (A33).
 */
@Serializable
data class WelcomeMessage(
    @EncodeDefault val v: Int = 1,
    @EncodeDefault val type: String = "welcome",
    val session: String,
    @SerialName("robotd_version") val robotdVersion: String,
    @SerialName("rover_fw") @EncodeDefault val roverFw: String? = null,
    val limits: LimitsConfig,
    val safety: SafetyConfig,
) {
    init {
        require(v == 1) { "invalid v: $v" }
        require(type == "welcome") { "invalid type: $type" }
        require(Regex("^[0-9a-f]{8}\$").matches(session)) { "invalid session: $session" }
        require(robotdVersion.length >= 1 && robotdVersion.length <= 32) {
            "invalid robotd_version: $robotdVersion"
        }
        require(roverFw == null || roverFw.length <= 32) { "invalid rover_fw: $roverFw" }
    }
}

/** The block placed after the image and before the utterance. */
@Serializable
data class WorldState(
    @SerialName("heading_deg") val headingDeg: Int,
    @SerialName("battery_pct") val batteryPct: Int,
    @SerialName("obstacle_ahead") val obstacleAhead: Boolean,
    @SerialName("front_range_cm") @EncodeDefault val frontRangeCm: Int? = null,
    val bumper: Boolean,
    val moving: Boolean,
    @SerialName("power_cap_pct") val powerCapPct: Int,
    @SerialName("last_result") @EncodeDefault val lastResult: ResultStatus? = null,
    @SerialName("last_scene") @EncodeDefault val lastScene: String = "",
    @SerialName("recently_seen") @EncodeDefault val recentlySeen: List<RecentlySeen> = emptyList(),
    @SerialName("allowed_skills") val allowedSkills: List<SkillName>,
    @SerialName("motion_budget_left") val motionBudgetLeft: MotionBudget,
) {
    init {
        require(headingDeg >= 0 && headingDeg <= 359) { "invalid heading_deg: $headingDeg" }
        require(batteryPct >= 0 && batteryPct <= 100) { "invalid battery_pct: $batteryPct" }
        require(frontRangeCm == null || (frontRangeCm >= 0 && frontRangeCm <= 400)) {
            "invalid front_range_cm: $frontRangeCm"
        }
        require(powerCapPct >= 5 && powerCapPct <= 30) { "invalid power_cap_pct: $powerCapPct" }
        require(lastScene.length <= 240) { "invalid last_scene: $lastScene" }
        require(recentlySeen.size <= 8) { "invalid recently_seen: $recentlySeen" }
        require(allowedSkills.size >= 1) { "invalid allowed_skills: $allowedSkills" }
    }
}
