"""Emit kotlinx.serialization classes for the phone host from ``rover_contracts``.

Reads ``model_json_schema()`` of the contract models the phone will speak -- the
``SkillCall`` branches and their args, ``WorldState``, the two observations and
the bus messages -- and writes them as ``@Serializable`` data classes and enum
classes to ``hosts/android/link/src/main/kotlin/dev/rover/contracts/Generated.kt``.
Every bound in the schema becomes an ``init { require(...) }``, so the phone
refuses at construction what the Pi refuses at parse time.

Run from the repository root::

    PYTHONPATH=packages .venv/bin/python tools/gen_kotlin.py          # write
    PYTHONPATH=packages .venv/bin/python tools/gen_kotlin.py --check  # exit 1 if stale

Only the JSON schema is read.  Cross-field rules written as pydantic model
validators (``power != 0``, ``args`` matching ``skill``, ordered limits) are not
in the schema and are not generated; the generated header says so.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass, field
from enum import StrEnum
from pathlib import Path
from typing import Any, get_args

from pydantic import BaseModel
from rover_contracts import config, messages, observations, worldstate
from rover_contracts.messages import (
    EstopMessage,
    HelloMessage,
    ResultDetail,
    ResultMessage,
    SkillCall,
    SkillMessage,
    StateActive,
    StateBattery,
    StateBudget,
    StateMessage,
    StateRover,
    StateTwist,
    StopMessage,
    TwistMessage,
    TwistPayload,
    WelcomeMessage,
)
from rover_contracts.observations import FindObservation, SceneObservation
from rover_contracts.worldstate import MotionBudget, RecentlySeen, WorldState

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "hosts/android/link/src/main/kotlin/dev/rover/contracts/Generated.kt"
PACKAGE = "dev.rover.contracts"

# The roots.  Everything they reference (args, enums, welcome's config sections)
# arrives through their ``$defs`` and is emitted too.
ROOTS: tuple[type[BaseModel], ...] = (
    *get_args(get_args(SkillCall)[0]),
    WorldState,
    RecentlySeen,
    MotionBudget,
    SceneObservation,
    FindObservation,
    SkillMessage,
    TwistMessage,
    TwistPayload,
    StopMessage,
    EstopMessage,
    StateMessage,
    StateRover,
    StateTwist,
    StateBattery,
    StateActive,
    StateBudget,
    ResultMessage,
    ResultDetail,
    WelcomeMessage,
    HelloMessage,
)

# Python enum classes by name, so a Kotlin member keeps the Python member's name
# (``ResultReason.NONE`` for ``""``) rather than one derived from its value.
ENUMS: dict[str, type[StrEnum]] = {
    name: obj
    for module in (messages, worldstate, observations, config)
    for name, obj in vars(module).items()
    if isinstance(obj, type) and issubclass(obj, StrEnum)
}

KOTLIN_KEYWORDS = frozenset({
    "as", "break", "class", "continue", "do", "else", "false", "for", "fun", "if", "in",
    "interface", "is", "null", "object", "package", "return", "super", "this", "throw",
    "true", "try", "typealias", "typeof", "val", "var", "when", "while",
})

HEADER = """\
// GENERATED by tools/gen_kotlin.py from the pydantic models in
// packages/rover_contracts -- do not edit by hand.
//
// Regenerate, from the repository root:
//   PYTHONPATH=packages .venv/bin/python tools/gen_kotlin.py
// Check for drift (exit 1 when this file is stale):
//   PYTHONPATH=packages .venv/bin/python tools/gen_kotlin.py --check
//
// Every bound the Pi enforces at parse time is an `init { require(...) }`
// here: numeric ranges, string lengths and patterns, list sizes, literal
// constants and closed string sets.  Cross-field rules written as pydantic
// model validators (power != 0, args matching skill, ordered limits) are not
// in the JSON schema and are NOT generated; a host built on these classes
// must add them in its own validator.
//
// Mapping: an integer with a closed range that fits Int -> Int, any other
// integer -> Long; number -> Double; a closed string enum -> enum class with
// @SerialName; X | null -> X?; an untagged union -> JsonObject.  Every property
// with a default carries @EncodeDefault, so an encoded object has every key
// pydantic's model_dump() emits, in the same order.  Decode with the default
// Json(): unknown keys, lenient literals and NaN/Infinity are then refused, as
// extra="forbid" and allow_inf_nan=False refuse them on the Pi.
//
// Order: enums first, then classes, each sorted by name; properties in the
// pydantic declaration order.
"""


@dataclass
class Prop:
    json_name: str
    kname: str
    ktype: str
    nullable: bool
    default: str | None
    checks: list[str] = field(default_factory=list)
    doc: str | None = None


def collect_defs() -> dict[str, dict[str, Any]]:
    """One definition per title, from every root's ``model_json_schema()``."""
    defs: dict[str, dict[str, Any]] = {}

    def add(name: str, schema: dict[str, Any]) -> None:
        if name in defs and defs[name] != schema:
            sys.exit(f"gen_kotlin: two different definitions of {name}")
        defs[name] = schema

    for model in ROOTS:
        schema = model.model_json_schema()
        for name, sub in schema.pop("$defs", {}).items():
            add(name, sub)
        add(schema["title"], schema)
    return defs


def is_enum(schema: dict[str, Any]) -> bool:
    return "enum" in schema and schema.get("type") == "string"


def ref_name(schema: dict[str, Any]) -> str:
    return schema["$ref"].rsplit("/", 1)[1]


def camel(name: str) -> str:
    head, *rest = name.split("_")
    kname = head + "".join(part[:1].upper() + part[1:] for part in rest)
    return kname + "_" if kname in KOTLIN_KEYWORDS else kname


def kstr(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")
    return f'"{escaped}"'


def lit(value: Any, ktype: str) -> str:
    if ktype == "Boolean":
        return "true" if value else "false"
    if ktype == "Int":
        return str(int(value))
    if ktype == "Long":
        return f"{int(value)}L"
    if ktype == "Double":
        return repr(float(value))
    if ktype == "String":
        return kstr(value)
    sys.exit(f"gen_kotlin: no literal for {value!r} as {ktype}")


def int_type(schema: dict[str, Any]) -> str:
    lo = schema.get("minimum", schema.get("exclusiveMinimum"))
    hi = schema.get("maximum", schema.get("exclusiveMaximum"))
    if lo is not None and hi is not None and lo >= -(2**31) and hi <= 2**31 - 1:
        return "Int"
    return "Long"


def bound_checks(schema: dict[str, Any], ktype: str, expr: str) -> list[str]:
    out: list[str] = []
    if "enum" in schema:
        members = ", ".join(kstr(v) for v in schema["enum"])
        out.append(f"{expr} in setOf({members})")
    for key, op in (
        ("minimum", ">="),
        ("exclusiveMinimum", ">"),
        ("maximum", "<="),
        ("exclusiveMaximum", "<"),
    ):
        if key in schema:
            out.append(f"{expr} {op} {lit(schema[key], ktype)}")
    if "minLength" in schema:
        out.append(f"{expr}.length >= {schema['minLength']}")
    if "maxLength" in schema:
        out.append(f"{expr}.length <= {schema['maxLength']}")
    if "pattern" in schema:
        out.append(f"Regex({kstr(schema['pattern'])}).matches({expr})")
    return out


def kotlin_of(schema: dict[str, Any], expr: str) -> tuple[str, list[str]]:
    """Kotlin type and the checks on ``expr`` for a schema that is not null."""
    if "$ref" in schema:
        return ref_name(schema), []
    if "const" in schema:
        const = schema["const"]
        ktype = {bool: "Boolean", int: "Int", str: "String"}[type(const)]
        return ktype, [f"{expr} == {lit(const, ktype)}"]
    kind = schema.get("type")
    if kind == "array":
        item_type, item_checks = kotlin_of(schema["items"], "it")
        checks = []
        if "minItems" in schema:
            checks.append(f"{expr}.size >= {schema['minItems']}")
        if "maxItems" in schema:
            checks.append(f"{expr}.size <= {schema['maxItems']}")
        if item_checks:
            checks.append(f"{expr}.all {{ {' && '.join(item_checks)} }}")
        return f"List<{item_type}>", checks
    ktype = {
        "integer": int_type(schema),
        "number": "Double",
        "string": "String",
        "boolean": "Boolean",
    }.get(kind or "")
    if ktype is None:
        sys.exit(f"gen_kotlin: unsupported schema {schema!r}")
    return ktype, bound_checks(schema, ktype, expr)


def default_of(value: Any, ktype: str, defs: dict[str, Any]) -> str:
    if value is None:
        return "null"
    if ktype in defs and is_enum(defs[ktype]):
        return f"{ktype}.{member_name(ktype, defs[ktype], value)}"
    if isinstance(value, list):
        if value:
            sys.exit(f"gen_kotlin: non-empty list default {value!r}")
        return "emptyList()"
    return lit(value, ktype)


def resolve(
    name: str, schema: dict[str, Any], required: bool, defs: dict[str, Any]
) -> Prop:
    kname = camel(name)
    inner = schema
    nullable = False
    if "anyOf" in schema:
        branches = schema["anyOf"]
        non_null = [b for b in branches if b.get("type") != "null"]
        nullable = len(non_null) < len(branches)
        if len(non_null) == 1:
            inner = non_null[0]
        elif all("$ref" in b for b in non_null):
            names = ", ".join(ref_name(b) for b in non_null)
            prop = Prop(name, kname, "JsonObject", nullable, None)
            prop.doc = (
                f"One of {names}, untagged: decode with the class the "
                "sibling discriminator selects."
            )
            inner = {}
            if nullable:
                prop.ktype += "?"
            return finish(prop, schema, required, defs)
        else:
            sys.exit(f"gen_kotlin: unsupported union for {name}: {schema!r}")
    ktype, checks = kotlin_of(inner, kname)
    prop = Prop(name, kname, ktype + ("?" if nullable else ""), nullable, None, checks)
    return finish(prop, schema, required, defs)


def finish(
    prop: Prop, schema: dict[str, Any], required: bool, defs: dict[str, Any]
) -> Prop:
    base = prop.ktype.rstrip("?")
    if "default" in schema:
        prop.default = default_of(schema["default"], base, defs)
    elif not required:
        if prop.nullable:
            prop.default = "null"
        elif base.startswith("List<"):
            prop.default = "emptyList()"
        else:
            sys.exit(f"gen_kotlin: {prop.json_name} is optional with no default")
    return prop


def member_name(enum_name: str, schema: dict[str, Any], value: str) -> str:
    python_enum = ENUMS.get(enum_name)
    if python_enum is not None:
        return python_enum(value).name
    derived = "".join(ch if ch.isalnum() else "_" for ch in value).strip("_").upper()
    if not derived or derived[0].isdigit():
        sys.exit(f"gen_kotlin: cannot name enum member for {value!r} in {enum_name}")
    return derived


def kdoc(text: str | None, indent: str = "") -> list[str]:
    if not text:
        return []
    lines = text.strip().replace("*/", "* /").splitlines()
    if len(lines) == 1:
        return [f"{indent}/** {lines[0]} */"]
    body = [f"{indent} * {line}".rstrip() for line in lines]
    return [f"{indent}/**", *body, f"{indent} */"]


def emit_enum(name: str, schema: dict[str, Any]) -> list[str]:
    lines = [*kdoc(schema.get("description")), "@Serializable", f"enum class {name} {{"]
    for value in schema["enum"]:
        member = member_name(name, schema, value)
        lines.append(f"    @SerialName({kstr(value)}) {member},")
    lines.append("}")
    return lines


def emit_class(name: str, schema: dict[str, Any], defs: dict[str, Any]) -> list[str]:
    required = set(schema.get("required", []))
    props = [
        resolve(pname, pschema, pname in required, defs)
        for pname, pschema in schema.get("properties", {}).items()
    ]
    lines = [*kdoc(schema.get("description")), "@Serializable"]
    if not props:
        lines.append(f"object {name}")
        return lines
    lines.append(f"data class {name}(")
    for prop in props:
        lines += kdoc(prop.doc, "    ")
        parts = []
        if prop.kname != prop.json_name:
            parts.append(f"@SerialName({kstr(prop.json_name)})")
        if prop.default is not None:
            parts.append("@EncodeDefault")
        decl = f"val {prop.kname}: {prop.ktype}"
        if prop.default is not None:
            decl += f" = {prop.default}"
        lines.append("    " + " ".join([*parts, decl]) + ",")
    checked = [p for p in props if p.checks]
    if not checked:
        lines.append(")")
        return lines
    lines += [") {", "    init {"]
    for prop in checked:
        cond = " && ".join(prop.checks)
        if prop.nullable:
            if len(prop.checks) > 1:
                cond = f"({cond})"
            cond = f"{prop.kname} == null || {cond}"
        message = f'"invalid {prop.json_name}: ${prop.kname}"'
        one_line = f"        require({cond}) {{ {message} }}"
        if len(one_line) <= 100:
            lines.append(one_line)
        else:
            lines.append(f"        require({cond}) {{")
            lines.append(f"            {message}")
            lines.append("        }")
    lines += ["    }", "}"]
    return lines


def render() -> str:
    defs = collect_defs()
    enums = sorted(name for name, d in defs.items() if is_enum(d))
    classes = sorted(name for name, d in defs.items() if not is_enum(d))
    for name in classes:
        if defs[name].get("type") != "object":
            sys.exit(f"gen_kotlin: {name} is neither an object nor a string enum")
    body: list[str] = []
    for name in enums:
        body += emit_enum(name, defs[name]) + [""]
    for name in classes:
        body += emit_class(name, defs[name], defs) + [""]
    text = "\n".join(body)

    imports = ["kotlinx.serialization.SerialName", "kotlinx.serialization.Serializable"]
    file_annotations = []
    if "@EncodeDefault" in text:
        imports += [
            "kotlinx.serialization.EncodeDefault",
            "kotlinx.serialization.ExperimentalSerializationApi",
        ]
        file_annotations.append("@file:OptIn(ExperimentalSerializationApi::class)")
    if "JsonObject" in text:
        imports.append("kotlinx.serialization.json.JsonObject")
    head = [HEADER]
    if file_annotations:
        head += file_annotations + [""]
    head += [f"package {PACKAGE}", ""]
    head += [f"import {imp}" for imp in sorted(imports)]
    head.append("")
    return "\n".join(head) + "\n" + text


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--out", type=Path, default=OUT, help=f"default {OUT.relative_to(REPO)}"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 when the file on disk differs from what would be generated",
    )
    args = parser.parse_args(argv)
    text = render()
    if args.check:
        current = args.out.read_text() if args.out.exists() else None
        if current != text:
            state = "stale" if current is not None else "missing"
            hint = "run tools/gen_kotlin.py and commit"
            print(f"{args.out}: {state}; {hint}", file=sys.stderr)
            return 1
        print(f"{args.out}: up to date")
        return 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)
    print(f"wrote {args.out} ({text.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
